apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mysql-ns
spec:
  selector:
    app: mysql
  type: LoadBalancer
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
    nodePort: 30000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: mysql-ns
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql-root-password
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /tmp/mysql-pv
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc